(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},p=ba(this),q=function(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&l(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(k,m){this.g=k;l(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(k){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(k||"")+"_"+d++,k)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});
var ca=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},da=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},t;
if("function"==typeof Object.setPrototypeOf)t=Object.setPrototypeOf;else{var u;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;u=ha.a;break a}catch(a){}u=!1}t=u?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ia=t,v=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype},w=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(g){var h=typeof g;return"object"===h&&null!==g||"function"===h}function d(g){if(!w(g,k)){var h=new b;l(g,k,{value:h})}}function e(g){var h=Object[g];h&&(Object[g]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return h(n)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),n=new a([[g,2],[h,3]]);if(2!=n.get(g)||3!=n.get(h))return!1;n.delete(g);n.set(h,4);return!n.has(g)&&4==n.get(h)}catch(A){return!1}}())return a;
var k="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var m=0,f=function(g){this.g=(m+=Math.random()+1).toString();if(g){g=r(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};f.prototype.set=function(g,h){if(!c(g))throw Error("Invalid WeakMap key");d(g);if(!w(g,k))throw Error("WeakMap key fail: "+g);g[k][this.g]=h;return this};f.prototype.get=function(g){return c(g)&&w(g,k)?g[k][this.g]:void 0};f.prototype.has=function(g){return c(g)&&w(g,k)&&w(g[k],this.g)};
f.prototype.delete=function(g){return c(g)&&w(g,k)&&w(g[k],this.g)?delete g[k][this.g]:!1};return f});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),g=new a(r([[f,"s"]]));if("s"!=g.get(f)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var h=g.entries(),n=h.next();if(n.done||n.value[0]!=f||"s"!=n.value[1])return!1;n=h.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!h.next().done?!1:!0}catch(A){return!1}}())return a;var b=new WeakMap,c=function(f){this.h={};this.g=k();
this.size=0;if(f){f=r(f);for(var g;!(g=f.next()).done;)g=g.value,this.set(g[0],g[1])}};c.prototype.set=function(f,g){f=0===f?0:f;var h=d(this,f);h.list||(h.list=this.h[h.id]=[]);h.i?h.i.value=g:(h.i={next:this.g,l:this.g.l,head:this.g,key:f,value:g},h.list.push(h.i),this.g.l.next=h.i,this.g.l=h.i,this.size++);return this};c.prototype.delete=function(f){f=d(this,f);return f.i&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.h[f.id],f.i.l.next=f.i.next,f.i.next.l=f.i.l,f.i.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.l=k();this.size=0};c.prototype.has=function(f){return!!d(this,f).i};c.prototype.get=function(f){return(f=d(this,f).i)&&f.value};c.prototype.entries=function(){return e(this,function(f){return[f.key,f.value]})};c.prototype.keys=function(){return e(this,function(f){return f.key})};c.prototype.values=function(){return e(this,function(f){return f.value})};c.prototype.forEach=function(f,g){for(var h=this.entries(),n;!(n=h.next()).done;)n=n.value,
f.call(g,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(f,g){var h=g&&typeof g;"object"==h||"function"==h?b.has(g)?h=b.get(g):(h=""+ ++m,b.set(g,h)):h="p_"+g;var n=f.h[h];if(n&&w(f.h,h))for(f=0;f<n.length;f++){var A=n[f];if(g!==g&&A.key!==A.key||g===A.key)return{id:h,list:n,index:f,i:A}}return{id:h,list:n,index:-1,i:void 0}},e=function(f,g){var h=f.g;return ca(function(){if(h){for(;h.head!=f.g;)h=h.l;for(;h.next!=h.head;)return h=h.next,{done:!1,value:g(h)};h=null}return{done:!0,
value:void 0}})},k=function(){var f={};return f.l=f.next=f.head=f},m=0;return c});q("globalThis",function(a){return a||p});q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(f){return f};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var m=0;!(k=b.next()).done;)e.push(c.call(d,k.value,m++))}else for(k=b.length,m=0;m<k;m++)e.push(c.call(d,b[m],m));return e}});var x=this||self,y=function(a){return a};var ja=new function(a,b){this.g=a;this.defaultValue=void 0===b?!1:b}(370946349),ka=new function(a,b){this.g=a;this.defaultValue=void 0===b?0:b}(406149835),la=new function(a,b){b=void 0===b?[]:b;this.g=a;this.defaultValue=b}(1932,["AxujKG9INjsZ8/gUq8+dTruNvk7RjZQ1oFhhgQbcTJKDnZfbzSTE81wvC2Hzaf3TW4avA76LTZEMdiedF1vIbA4AAABueyJvcmlnaW4iOiJodHRwczovL2ltYXNkay5nb29nbGVhcGlzLmNvbTo0NDMiLCJmZWF0dXJlIjoiVHJ1c3RUb2tlbnMiLCJleHBpcnkiOjE2NTI3NzQ0MDAsImlzVGhpcmRQYXJ0eSI6dHJ1ZX0=","Azuce85ORtSnWe1MZDTv68qpaW3iHyfL9YbLRy0cwcCZwVnePnOmkUJlG8HGikmOwhZU22dElCcfrfX2HhrBPAkAAAB7eyJvcmlnaW4iOiJodHRwczovL2RvdWJsZWNsaWNrLm5ldDo0NDMiLCJmZWF0dXJlIjoiVHJ1c3RUb2tlbnMiLCJleHBpcnkiOjE2NTI3NzQ0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9",
"A16nvcdeoOAqrJcmjLRpl1I6f3McDD8EfofAYTt/P/H4/AWwB99nxiPp6kA0fXoiZav908Z8etuL16laFPUdfQsAAACBeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiVHJ1c3RUb2tlbnMiLCJleHBpcnkiOjE2NTI3NzQ0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9","AxBHdr0J44vFBQtZUqX9sjiqf5yWZ/OcHRcRMN3H9TH+t90V/j3ENW6C8+igBZFXMJ7G3Pr8Dd13632aLng42wgAAACBeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXN5bmRpY2F0aW9uLmNvbTo0NDMiLCJmZWF0dXJlIjoiVHJ1c3RUb2tlbnMiLCJleHBpcnkiOjE2NTI3NzQ0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9",
"A88BWHFjcawUfKU3lIejLoryXoyjooBXLgWmGh+hNcqMK44cugvsI5YZbNarYvi3roc1fYbHA1AVbhAtuHZflgEAAAB2eyJvcmlnaW4iOiJodHRwczovL2dvb2dsZS5jb206NDQzIiwiZmVhdHVyZSI6IlRydXN0VG9rZW5zIiwiZXhwaXJ5IjoxNjUyNzc0NDAwLCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ=="]);var ma=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var oa={},z=null;var pa="undefined"!==typeof Uint8Array;var B="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function qa(a){var b;B?b=a[B]:b=a.s;return null==b?0:b}function C(a){Object.isFrozen(a)||(B?a[B]|=1:void 0!==a.s?a.s|=1:Object.defineProperties(a,{s:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function ra(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var sa,ta=Object.freeze(C([])),ua=function(a){a=a.j;if(Array.isArray(a)&&qa(a)&2)throw Error("Cannot mutate an immutable Message");},va="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function wa(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function xa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&pa&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!z){z={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var k=c.concat(d[e].split(""));oa[e]=k;for(var m=0;m<k.length;m++){var f=k[m];void 0===z[f]&&(z[f]=m)}}}b=oa[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=k=0;k<a.length-2;k+=
3){var g=a[k],h=a[k+1];f=a[k+2];m=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|f>>6];f=b[f&63];c[e++]=m+g+h+f}m=0;f=d;switch(a.length-k){case 2:m=a[k+1],f=b[(m&15)<<2]||d;case 1:a=a[k],c[e]=b[a>>2]+b[(a&3)<<4|m>>4]+f+d}return c.join("")}}return a};function ya(a){var b=za;b=void 0===b?Aa:b;return Ba(a,b)}function Ca(a,b){if(null!=a){if(Array.isArray(a))a=Ba(a,b);else if(ra(a)){var c={},d;for(d in a)c[d]=Ca(a[d],b);a=c}else a=b(a);return a}}function Ba(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=Ca(c[d],b);Array.isArray(a)&&qa(a)&1&&C(c);return c}function za(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=xa(a);return Array.isArray(a)?ya(a):a}function Aa(a){return pa&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};var D=function(a,b,c,d){d=void 0===d?!1:d;ua(a);b<a.h&&!d?a.j[b+a.g]=c:(a.m||(a.m=a.j[a.h+a.g]={}))[b]=c;return a};var E=function(a,b,c){a||(a=Da);Da=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.g=(d?0:-1)-(this.constructor.g||0);this.o=void 0;this.j=a;a:{d=this.j.length;a=d-1;if(d&&(d=this.j[a],ra(d))){this.h=a-this.g;this.m=d;break a}void 0!==b&&-1<b?(this.h=Math.max(b,a+1-this.g),this.m=void 0):this.h=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.h)a+=this.g,(d=this.j[a])?Array.isArray(d)&&C(d):this.j[a]=ta;else{d=this.m||(this.m=this.j[this.h+this.g]={});var e=d[a];e?Array.isArray(e)&&
C(e):d[a]=ta}};E.prototype.toJSON=function(){var a=this.j;return sa?a:ya(a)};E.prototype.toString=function(){return this.j.toString()};function Ea(a,b){return xa(b)}var Da;var F=function(){E.apply(this,arguments)};v(F,E);if(va){var Fa={};Object.defineProperties(F,(Fa[Symbol.hasInstance]=wa(function(){throw Error("Cannot perform instanceof checks for MutableMessage");}),Fa))};var G=function(){F.apply(this,arguments)};v(G,F);if(va){var Ga={};Object.defineProperties(G,(Ga[Symbol.hasInstance]=wa(Object[Symbol.hasInstance]),Ga))};var H,Ha=function(){if(void 0===H){var a=null,b=x.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:y,createScript:y,createScriptURL:y})}catch(c){x.console&&x.console.error(c.message)}H=a}else H=a}return H};var I=function(a,b){this.g=b===Ia?a:""};I.prototype.toString=function(){return this.g+""};var Ia={};var Ja={},J=function(a,b,c){this.g=c===Ja?a:""};J.prototype.toString=function(){return this.g.toString()};var La=function(){var a=Ka;return a instanceof J&&a.constructor===J?a.g:"type_error:SafeHtml"};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Oa=function(a,b){if(!Ma()){var c=Math.random();if(c<b)return c=Na(),a[Math.floor(c*a.length)]}return null},Na=function(){if(!globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},Pa=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)},Ma=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return na(["Google Web Preview","Mediapartners-Google",
"Google-Read-Aloud","Google-Adwords"],Qa)||1E-4>Math.random()}),Qa=function(a){var b;a:{if(b=x.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)},Ta=function(){var a=K,b=Ra;0!=b.length&&a.head&&b.forEach(function(c){if(c&&c&&a.head){var d=Sa("META");a.head.appendChild(d);d.httpEquiv="origin-trial";d.content=c}})},Ua=function(){var a=window;if("number"!==typeof a.goog_pvsid)try{Object.defineProperty(a,"goog_pvsid",{value:Math.floor(Math.random()*Math.pow(2,52)),configurable:!1})}catch(b){}return Number(a.goog_pvsid)||
-1},Sa=function(a,b){b=void 0===b?document:b;return b.createElement(String(a).toLowerCase())};function Va(a,b,c){a.google_image_requests||(a.google_image_requests=[]);var d=Sa("IMG",a.document);if(c){var e=function(){if(c){var k=a.google_image_requests,m=ma(k,d);0<=m&&Array.prototype.splice.call(k,m,1)}d.removeEventListener&&d.removeEventListener("load",e,!1);d.removeEventListener&&d.removeEventListener("error",e,!1)};d.addEventListener&&d.addEventListener("load",e,!1);d.addEventListener&&d.addEventListener("error",e,!1)}d.src=b;a.google_image_requests.push(d)}
var Xa=function(a){var b=void 0===b?!1:b;var c="https://pagead2.googlesyndication.com/pagead/gen_204?id=dtt_err";Pa(a,function(d,e){d&&(c+="&"+e+"="+encodeURIComponent(d))});Wa(c,b)},Wa=function(a,b){var c=window;b=void 0===b?!1:b;c.fetch?c.fetch(a,{keepalive:!0,credentials:"include",redirect:"follow",method:"get",mode:"no-cors"}):Va(c,a,void 0===b?!1:b)};var L=function(){var a=Ya,b="u";if(a.u&&a.hasOwnProperty(b))return a.u;b=new a;return a.u=b};var Ya=function(){var a={};this.g=function(){var b=ja.g,c=ja.defaultValue;return null!=a[b]?a[b]:c};this.h=function(){var b=ka.g,c=ka.defaultValue;return null!=a[b]?a[b]:c};this.m=function(){var b=la.g,c=la.defaultValue;return null!=a[b]?a[b]:c}};var Za=function(){};var $a=function(a){this.h=a;this.g=null};v($a,Za);var M={issuerOrigin:"https://attestation.android.com",issuancePath:"/att/i",redemptionPath:"/att/r"},N={issuerOrigin:"https://pagead2.googlesyndication.com",issuancePath:"/dtt/i",redemptionPath:"/dtt/r",getStatePath:"/dtt/s"};var Ra=L().m(),bb=function(a,b,c){var d=this;this.h=a;this.g=[];b&&ab()&&this.g.push(M);c&&this.g.push(N);if(document.hasTrustToken&&!L().g()){var e=new Map;this.g.forEach(function(k){e.set(k.issuerOrigin,{issuerOrigin:k.issuerOrigin,state:d.h?1:12,hasRedemptionRecord:!1})});window.goog_tt_state_map=window.goog_tt_state_map&&window.goog_tt_state_map instanceof Map?new Map([].concat(da(e),da(window.goog_tt_state_map))):e;window.goog_tt_promise_map&&window.goog_tt_promise_map instanceof Map||(window.goog_tt_promise_map=
new Map)}};v(bb,Za);
var ab=function(){var a=void 0===a?window:a;a=a.navigator.userAgent;var b=/Chrome/.test(a);return/Android/.test(a)&&b},O=function(a,b,c){var d,e=null==(d=window.goog_tt_state_map)?void 0:d.get(a);e&&(e.state=b,void 0!=c&&(e.hasRedemptionRecord=c))},cb=function(){var a=M.issuerOrigin+M.redemptionPath,b={keepalive:!0,trustToken:{type:"token-redemption",issuer:M.issuerOrigin,refreshPolicy:"none"}};O(M.issuerOrigin,2);return window.fetch(a,b).then(function(c){if(!c.ok)throw Error(c.status+": Network response was not ok!");
O(M.issuerOrigin,6,!0)}).catch(function(c){c&&"NoModificationAllowedError"===c.name?O(M.issuerOrigin,6,!0):O(M.issuerOrigin,5)})},db=function(){var a=M.issuerOrigin+M.issuancePath;O(M.issuerOrigin,8);return window.fetch(a,{keepalive:!0,trustToken:{type:"token-request"}}).then(function(b){if(!b.ok)throw Error(b.status+": Network response was not ok!");O(M.issuerOrigin,10);return cb()}).catch(function(b){if(b&&"NoModificationAllowedError"===b.name)return O(M.issuerOrigin,10),cb();O(M.issuerOrigin,9)})},
eb=function(){O(M.issuerOrigin,13);return document.hasTrustToken(M.issuerOrigin).then(function(a){return a?cb():db()})},fb=function(){O(N.issuerOrigin,13);if(window.Promise){var a=document.hasTrustToken(N.issuerOrigin).then(function(e){return e}).catch(function(e){return window.Promise.reject({state:19,error:e})}),b=N.issuerOrigin+N.redemptionPath,c={keepalive:!0,trustToken:{type:"token-redemption",refreshPolicy:"none"}};O(N.issuerOrigin,16);a=a.then(function(e){return window.fetch(b,c).then(function(k){if(!k.ok)throw Error(k.status+
": Network response was not ok!");O(N.issuerOrigin,18,!0)}).catch(function(k){if(k&&"NoModificationAllowedError"===k.name)O(N.issuerOrigin,18,!0);else{if(e)return window.Promise.reject({state:17,error:k});O(N.issuerOrigin,17)}})}).then(function(){return document.hasTrustToken(N.issuerOrigin).then(function(e){return e}).catch(function(e){return window.Promise.reject({state:19,error:e})})}).then(function(e){var k=N.issuerOrigin+N.getStatePath;O(N.issuerOrigin,20);return window.fetch(k+"?ht="+e,{trustToken:{type:"send-redemption-record",
issuers:[N.issuerOrigin]}}).then(function(m){if(!m.ok)throw Error(m.status+": Network response was not ok!");O(N.issuerOrigin,22);return m.text().then(function(f){return JSON.parse(f)})}).catch(function(m){return window.Promise.reject({state:21,error:m})})});var d=Ua();return a.then(function(e){var k=N.issuerOrigin+N.issuancePath;return e&&e.srqt&&e.cs?(O(N.issuerOrigin,23),window.fetch(k+"?cs="+e.cs+"&correlator="+d,{keepalive:!0,trustToken:{type:"token-request"}}).then(function(m){if(!m.ok)throw Error(m.status+
": Network response was not ok!");O(N.issuerOrigin,25);return e}).catch(function(m){return window.Promise.reject({state:24,error:m})})):e}).then(function(e){if(e&&e.srdt&&e.cs)return O(N.issuerOrigin,26),window.fetch(b+"?cs="+e.cs+"&correlator="+d,{keepalive:!0,trustToken:{type:"token-redemption",refreshPolicy:"refresh"}}).then(function(k){if(!k.ok)throw Error(k.status+": Network response was not ok!");O(N.issuerOrigin,28,!0)}).catch(function(k){return window.Promise.reject({state:27,error:k})})}).then(function(){O(N.issuerOrigin,
29)}).catch(function(e){if(e instanceof Object&&e.hasOwnProperty("state")&&e.hasOwnProperty("error"))if("number"===typeof e.state&&e.error instanceof Error){O(N.issuerOrigin,e.state);var k=L().h();Math.random()<=k&&Xa({state:e.state,err:e.error.toString()})}else throw Error(e);else throw e;})}},hb=function(){var a=gb;if(document.hasTrustToken&&!L().g()&&a.h){var b=window.goog_tt_promise_map;if(b&&b instanceof Map){var c=[];if(a.g.some(function(e){return e.issuerOrigin===M.issuerOrigin})){var d=b.get(M.issuerOrigin);
d||(d=eb(),b.set(M.issuerOrigin,d));c.push(d)}a.g.some(function(e){return e.issuerOrigin===N.issuerOrigin})&&(a=b.get(N.issuerOrigin),a||(a=fb(),b.set(N.issuerOrigin,a)),c.push(a));if(0<c.length&&window.Promise&&window.Promise.all)return window.Promise.all(c)}}};var jb=function(a){G.call(this,a,-1,ib)};v(jb,G);var kb=function(a,b){return D(a,2,b)},lb=function(a,b){return D(a,3,b)},mb=function(a,b){return D(a,4,b)},nb=function(a,b){return D(a,5,b)},ob=function(a,b){return D(a,9,b)},pb=function(a,b){var c=void 0===c?!1:c;ua(a);if(b){var d=C([]);for(var e=0;e<b.length;e++)d[e]=b[e].j;a.o||(a.o={});a.o[10]=b}else a.o&&(a.o[10]=void 0),d=ta;return D(a,10,d,c)},qb=function(a,b){return D(a,11,b)},rb=function(a,b){return D(a,1,b)},sb=function(a){G.call(this,a)};
v(sb,G);var ib=[10,6];var tb="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function ub(){var a;return null!=(a=x.google_tag_data)?a:x.google_tag_data={}}
function vb(){var a,b;if("function"!==typeof(null==(a=x.navigator)?void 0:null==(b=a.userAgentData)?void 0:b.getHighEntropyValues))return null;var c=ub();if(c.uach_promise)return c.uach_promise;a=x.navigator.userAgentData.getHighEntropyValues(tb).then(function(d){null!=c.uach||(c.uach=d);return d});return c.uach_promise=a}
function wb(a){var b;return qb(pb(ob(nb(mb(lb(kb(rb(new jb,a.platform||""),a.platformVersion||""),a.architecture||""),a.model||""),a.uaFullVersion||""),a.bitness||""),(null==(b=a.fullVersionList)?void 0:b.map(function(c){var d=new sb;d=D(d,1,c.brand);return D(d,2,c.version)}))||[]),a.wow64||!1)};var xb=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(d){}return!0}(x,!1)?"https:":"http:",yb={},zb=(yb[1]="A4/Htern2udN9w3yJK9QgWQxQFruxOXsXL7cW60DyCl0EZFGCSme/J33Q/WzF7bBkVvhEWDlcBiUyZaim5CpFQwAAACceyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQ29udmVyc2lvbk1lYXN1cmVtZW50IiwiZXhwaXJ5IjoxNjQzMTU1MTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlLCJ1c2FnZSI6InN1YnNldCJ9",
yb);var Ab={G:1,B:4,C:5,D:12,F:13,H:14},Bb={A:"40004006",v:"40004007"};function Cb(){return{1:.5,4:.02,5:.001,12:.001,13:.001,14:.001}}function Db(){var a=Eb,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in Ab)if(b=a[Ab[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Fb(){if(!x.dcmads.uach){var a=vb();a&&(x.dcmads.uachp=a.then(function(b){var c=x.dcmads;a:{b=wb(b);sa=!0;try{var d=JSON.stringify(b.toJSON(),Ea);break a}finally{sa=!1}d=void 0}c.uach=d}))}};try{x.dcmads=x.dcmads||{};x.dcmads.startTime=(new Date).getTime();var Gb=x.dcmads,P=x.dcmads.version,Q={loader:258};if(P)if(Q.experiment=P.experiment,88==P.number||"p"==P.number)Q.number=88;else if(88==P.number||"c"==P.number)Q.number=88;if(!Q.number){var Hb=Oa([88,88],0);Q.experiment=!!Hb;Q.number=Hb||88}Gb.version=Q;var Ib=x.dcmads,Jb,Eb=x.dcmads.expts,R;R=void 0===R?Cb:R;Jb=Db()?Eb:R();Ib.expts=Jb;var Kb=x.dcmads,Lb;var S=x.dcmads;if(null!=S.eids)Lb=S.eids;else{var Mb=[],Nb=x.navigator;if(Nb.connection&&
Nb.connection.saveData){var Ob=Oa([Bb.A,Bb.v],S.expts[4]);Ob&&Mb.push("4|"+Ob)}if(ab()){var Pb=Oa(["44761098","44761099","44761100","44761101"],S.expts[13]);Pb&&Mb.push("12|"+Pb)}Lb=Mb.join(",")}Kb.eids=Lb;x.dcmads.ots=zb;x.dcmads.tts=0;Fb();if(RegExp("12\\|(44761099|44761100|44761101)").test(x.dcmads.eids)){var K=x.document;K=void 0===K?window.document:K;Ta();var T=new $a(x),Qb;if(!(Qb="function"===typeof T.h.__tcfapi)){var Rb;if(T.g)Rb=T.g;else{var Sb;b:{for(var U=T.h,Tb=0;50>Tb;++Tb){var Ub;try{Ub=
!(!U.frames||!U.frames.__tcfapiLocator)}catch(a){Ub=!1}if(Ub){Sb=U;break b}var Vb;c:{try{var Wb=U.parent;if(Wb&&Wb!=U){Vb=Wb;break c}}catch(a){}Vb=null}if(!(U=Vb))break}Sb=null}T.g=Sb;Rb=T.g}Qb=null!=Rb}if(Qb)x.dcmads.tts=1;else{x.dcmads.tts=2;var gb=new bb(!0,!0,!0);x.dcmads.ttp=hb()}}var Xb=new RegExp("4\\|"+Bb.v),Yb=x.dcmads.version,Zb=Yb.number,$b="";Yb.experiment&&88==Zb&&($b="?rxp=88x88");var ac="impl_v"+Zb+".js"+$b,bc=x.document,cc=bc.currentScript||Array.from(bc.getElementsByTagName("script")).pop(),
dc=(0==(cc&&cc.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+ac;if(Xb.test(x.dcmads.eids)){var ec=x.document,fc=Ha(),gc=fc?fc.createScriptURL(dc):dc,V=Sa("SCRIPT",ec),hc=new I(gc,Ia);V.src=hc instanceof I&&hc.constructor===I?hc.g:"type_error:TrustedResourceUrl";var ic,jc,kc,lc=null==(kc=(jc=(V.ownerDocument&&V.ownerDocument.defaultView||window).document).querySelector)?void 0:kc.call(jc,"script[nonce]");(ic=lc?lc.nonce||lc.getAttribute("nonce")||"":"")&&V.setAttribute("nonce",
ic);var W=ec.getElementsByTagName("script")[0];W&&W.parentNode&&W.parentNode.insertBefore(V,W)}else{var mc=x.document,Ka,nc='<script src="'+dc+'">\x3c/script>',oc=Ha(),pc=oc?oc.createHTML(nc):nc;Ka=new J(pc,null,Ja);mc.write(Ka instanceof J?La():La())}}catch(a){if(.01>Math.random()){var qc="";try{var X,Y=a.toString();a.name&&-1==Y.indexOf(a.name)&&(Y+=": "+a.name);a.message&&-1==Y.indexOf(a.message)&&(Y+=": "+a.message);if(a.stack){var Z=a.stack,rc=Y;try{-1==Z.indexOf(rc)&&(Z=rc+"\n"+Z);for(var sc;Z!=
sc;)sc=Z,Z=Z.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");Y=Z.replace(/\n */g,"\n")}catch(b){Y=rc}}X=Y;X=X.substring(0,1024);qc=encodeURIComponent(X)}catch(b){qc="extr"}var tc=x.dcmads.eids,uc=document.createElement("img");uc.src=xb+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=258&context=554"+((tc?"&eids="+tc:"")+"&msg="+qc);(x.google_image_requests=x.google_image_requests||[]).push(uc)}};}).call(this);
