(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},q=ca(this),r=function(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
r("Symbol",function(a){if(a)return a;var b=function(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},t=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea=function(a){if(!(a instanceof Array)){a=t(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ka="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},la;
if("function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={a:!0},oa={};try{oa.__proto__=na;ma=oa.a;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var pa=la,u=function(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ha=b.prototype},qa=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};
r("Promise",function(a){function b(){this.g=null}function c(h){return h instanceof e?h:new e(function(g){g(h)})}if(a)return a;b.prototype.h=function(h){if(null==this.g){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(h)};var d=q.setTimeout;b.prototype.i=function(h){d(h,0)};b.prototype.l=function(){for(;this.g&&this.g.length;){var h=this.g;this.g=[];for(var g=0;g<h.length;++g){var k=h[g];h[g]=null;try{k()}catch(l){this.j(l)}}}this.g=null};b.prototype.j=function(h){this.i(function(){throw h;
})};var e=function(h){this.h=0;this.i=void 0;this.g=[];this.v=!1;var g=this.j();try{h(g.resolve,g.reject)}catch(k){g.reject(k)}};e.prototype.j=function(){function h(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:h(this.D),reject:h(this.l)}};e.prototype.D=function(h){if(h===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof e)this.J(h);else{a:switch(typeof h){case "object":var g=null!=h;break a;case "function":g=!0;break a;default:g=!1}g?
this.C(h):this.s(h)}};e.prototype.C=function(h){var g=void 0;try{g=h.then}catch(k){this.l(k);return}"function"==typeof g?this.K(g,h):this.s(h)};e.prototype.l=function(h){this.A(2,h)};e.prototype.s=function(h){this.A(1,h)};e.prototype.A=function(h,g){if(0!=this.h)throw Error("Cannot settle("+h+", "+g+"): Promise already settled in state"+this.h);this.h=h;this.i=g;2===this.h&&this.F();this.B()};e.prototype.F=function(){var h=this;d(function(){if(h.I()){var g=q.console;"undefined"!==typeof g&&g.error(h.i)}},
1)};e.prototype.I=function(){if(this.v)return!1;var h=q.CustomEvent,g=q.Event,k=q.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof g?h=new g("unhandledrejection",{cancelable:!0}):(h=q.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.i;return k(h)};e.prototype.B=function(){if(null!=this.g){for(var h=0;h<this.g.length;++h)f.h(this.g[h]);this.g=null}};
var f=new b;e.prototype.J=function(h){var g=this.j();h.V(g.resolve,g.reject)};e.prototype.K=function(h,g){var k=this.j();try{h.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(h,g){function k(n,v){return"function"==typeof n?function(A){try{l(n(A))}catch(L){m(L)}}:v}var l,m,p=new e(function(n,v){l=n;m=v});this.V(k(h,l),k(g,m));return p};e.prototype.catch=function(h){return this.then(void 0,h)};e.prototype.V=function(h,g){function k(){switch(l.h){case 1:h(l.i);break;case 2:g(l.i);
break;default:throw Error("Unexpected state: "+l.h);}}var l=this;null==this.g?f.h(k):this.g.push(k);this.v=!0};e.resolve=c;e.reject=function(h){return new e(function(g,k){k(h)})};e.race=function(h){return new e(function(g,k){for(var l=t(h),m=l.next();!m.done;m=l.next())c(m.value).V(g,k)})};e.all=function(h){var g=t(h),k=g.next();return k.done?c([]):new e(function(l,m){function p(A){return function(L){n[A]=L;v--;0==v&&l(n)}}var n=[],v=0;do n.push(void 0),v++,c(k.value).V(p(n.length-1),m),k=g.next();
while(!k.done)})};return e});var w=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
r("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!w(k,f)){var l=new b;ba(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=t(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!w(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};g.prototype.get=function(k){return c(k)&&w(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&w(k,f)&&w(k[f],this.g)};
g.prototype.delete=function(k){return c(k)&&w(k,f)&&w(k[f],this.g)?delete k[f][this.g]:!1};return g});
r("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(t([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!l.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(g){this.h={};this.g=f();
this.size=0;if(g){g=t(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.h[l.id]=[]);l.o?l.o.value=k:(l.o={next:this.g,H:this.g.H,head:this.g,key:g,value:k},l.list.push(l.o),this.g.H.next=l.o,this.g.H=l.o,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.o&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.h[g.id],g.o.H.next=g.o.next,g.o.next.H=g.o.H,g.o.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.H=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).o};c.prototype.get=function(g){return(g=d(this,g).o)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
g.call(k,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++h,b.set(k,l)):l="p_"+k;var m=g.h[l];if(m&&w(g.h,l))for(g=0;g<m.length;g++){var p=m[g];if(k!==k&&p.key!==p.key||k===p.key)return{id:l,list:m,index:g,o:p}}return{id:l,list:m,index:-1,o:void 0}},e=function(g,k){var l=g.g;return da(function(){if(l){for(;l.head!=g.g;)l=l.H;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.H=g.next=g.head=g},h=0;return c});r("globalThis",function(a){return a||q});
var x=this||self,ra=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},ta=function(a,b){function c(){}c.prototype=b.prototype;a.Ha=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ua=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}},ua=function(a){return a};function z(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}ta(z,Error);z.prototype.name="CustomError";function va(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])}ta(va,z);va.prototype.name="AssertionError";var wa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ea=function(a){if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Da,"&#0;"));return a},ya=/&/g,za=/</g,Aa=/>/g,Ba=/"/g,Ca=/'/g,Da=/\x00/g,xa=
/[\x00&<>"']/;function Fa(){var a=x.navigator;return a&&(a=a.userAgent)?a:""};var Ga=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ha=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Ia=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Pa=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;Ha(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},Qa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,
d[e],e,a))return!0;return!1};function Ra(a){for(var b=[],c=0;c<a;c++)b[c]="";return b};var Sa=function(a){Sa[" "](a);return a};Sa[" "]=function(){};var Ta=-1!=Fa().toLowerCase().indexOf("webkit")&&-1==Fa().indexOf("Edge");var Ua={},Va=null,Wa=function(a,b){void 0===b&&(b=0);if(!Va){Va={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Ua[e]=f;for(var h=0;h<f.length;h++){var g=f[h];void 0===Va[g]&&(Va[g]=h)}}}b=Ua[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var k=a[f],l=a[f+1];g=a[f+2];h=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[e++]=h+k+l+g}h=0;g=d;switch(a.length-
f){case 2:h=a[f+1],g=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+g+d}return c.join("")},Xa=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return Wa(b,3)};var Ya="undefined"!==typeof Uint8Array;var B="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function Za(a){var b;B?b=a[B]:b=a.W;return null==b?0:b}function $a(a){Object.isFrozen(a)||(B?a[B]|=1:void 0!==a.W?a.W|=1:Object.defineProperties(a,{W:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function ab(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var bb=Object.freeze($a([])),cb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function db(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function eb(a){var b=fb;b=void 0===b?gb:b;return hb(a,b)}function ib(a,b){if(null!=a){if(Array.isArray(a))a=hb(a,b);else if(ab(a)){var c={},d;for(d in a)c[d]=ib(a[d],b);a=c}else a=b(a);return a}}function hb(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=ib(c[d],b);Array.isArray(a)&&Za(a)&1&&$a(c);return c}
function fb(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":a&&!Array.isArray(a)&&Ya&&null!=a&&a instanceof Uint8Array&&(a=Wa(a))}return Array.isArray(a)?eb(a):a}function gb(a){return Ya&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};var jb=function(a,b,c){var d,e=a.g;if(Array.isArray(e)&&Za(e)&2)throw Error("Cannot mutate an immutable Message");b<a.j&&(void 0===d||!d)?a.g[b+a.h]=c:(a.i||(a.i=a.g[a.j+a.h]={}))[b]=c;return a},kb=function(a){a=5>=a.j?a.i?a.i[5]:void 0:a.g[5+a.h];return null==a?a:!!a};var mb=function(a,b,c){a||(a=lb);lb=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.h=(d?0:-1)-(this.constructor.g||0);this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],ab(d))){this.j=a-this.h;this.i=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.h),this.i=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.h,(d=this.g[a])?Array.isArray(d)&&$a(d):this.g[a]=bb;else{d=this.i||(this.i=this.g[this.j+this.h]={});var e=d[a];e?Array.isArray(e)&&$a(e):d[a]=
bb}};mb.prototype.toJSON=function(){return eb(this.g)};mb.prototype.toString=function(){return this.g.toString()};var lb;var nb=function(){mb.apply(this,arguments)};u(nb,mb);if(cb){var ob={};Object.defineProperties(nb,(ob[Symbol.hasInstance]=db(function(){throw Error("Cannot perform instanceof checks for MutableMessage");}),ob))};var pb=function(){nb.apply(this,arguments)};u(pb,nb);if(cb){var Gb={};Object.defineProperties(pb,(Gb[Symbol.hasInstance]=db(Object[Symbol.hasInstance]),Gb))};var C=function(a,b){this.h=a===Hb&&b||"";this.i=Ib};C.prototype.L=!0;C.prototype.g=function(){return this.h};var D=function(a){return a instanceof C&&a.constructor===C&&a.i===Ib?a.h:"type_error:Const"},Ib={},Hb={};var Jb=function(a){this.g=a;this.defaultValue=!1};var Kb=new Jb(370946349),Lb=new function(a,b){this.g=a;this.defaultValue=void 0===b?0:b}(406149835),Mb=new Jb(432946749);var Nb={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var Ob,Pb=function(){if(void 0===Ob){var a=null,b=x.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:ua,createScript:ua,createScriptURL:ua})}catch(c){x.console&&x.console.error(c.message)}Ob=a}else Ob=a}return Ob};var E=function(a,b){this.i=b===Qb?a:""};E.prototype.L=!0;E.prototype.g=function(){return this.i.toString()};E.prototype.$=!0;E.prototype.h=function(){return 1};E.prototype.toString=function(){return this.i+""};
var Rb=function(a){return a instanceof E&&a.constructor===E?a.i:"type_error:TrustedResourceUrl"},Vb=function(a){var b=D(new C(Hb,"https://cdn.ampproject.org/rtv/%{ampVersion}/amp4ads-host-v0.js"));if(!Sb.test(b))throw Error("Invalid TrustedResourceUrl format: "+b);var c=b.replace(Tb,function(d,e){if(!Object.prototype.hasOwnProperty.call(a,e))throw Error('Found marker, "'+e+'", in format string, "'+b+'", but no valid label mapping found in args: '+JSON.stringify(a));d=a[e];return d instanceof C?D(d):
encodeURIComponent(String(d))});return Ub(c)},Tb=/%{(\w+)}/g,Sb=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),Qb={},Ub=function(a){var b=Pb();a=b?b.createScriptURL(a):a;return new E(a,Qb)};var G=function(a,b){this.i=b===Wb?a:""};G.prototype.L=!0;G.prototype.g=function(){return this.i.toString()};G.prototype.$=!0;G.prototype.h=function(){return 1};G.prototype.toString=function(){return this.i.toString()};
var Xb=function(a){return a instanceof G&&a.constructor===G?a.i:"type_error:SafeUrl"},Yb=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,Zb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,$b=function(a){if(a instanceof G)return a;a="object"==typeof a&&a.L?a.g():String(a);Zb.test(a)?a=new G(a,Wb):(a=String(a),a=a.replace(/(%0A|%0D)/g,""),a=a.match(Yb)?new G(a,Wb):null);return a},Wb={},ac=new G("about:invalid#zClosurez",Wb);var bc={},H=function(a,b){this.h=b===bc?a:"";this.L=!0};H.prototype.g=function(){return this.h};H.prototype.toString=function(){return this.h.toString()};var cc=new H("",bc);
function dc(a){if(a instanceof G)return'url("'+Xb(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof C)a=D(a);else{a=String(a);var b=a.replace(ec,"$1").replace(ec,"$1").replace(fc,"url");if(gc.test(b)){if(b=!hc.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c&&ic(a)}a=b?jc(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new va("Value does not allow [{;}], got: %s.",[a]);return a}
function ic(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b}
var gc=RegExp("^[-,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$"),fc=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g"),ec=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g"),hc=/\/\*/;
function jc(a){return a.replace(fc,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(h,g,k){f=g;return k});b=($b(d)||ac).g();return c+f+b+f+e})};var kc={},K=function(a,b,c){this.i=c===kc?a:"";this.j=b;this.L=this.$=!0};K.prototype.h=function(){return this.j};K.prototype.g=function(){return this.i.toString()};K.prototype.toString=function(){return this.i.toString()};
var M=function(a){return a instanceof K&&a.constructor===K?a.i:"type_error:SafeHtml"},mc=function(a){if(a instanceof K)return a;var b="object"==typeof a,c=null;b&&a.$&&(c=a.h());return lc(Ea(b&&a.L?a.g():String(a)),c)},oc=function(a){var b=mc(nc),c=b.h(),d=[],e=function(f){Array.isArray(f)?f.forEach(e):(f=mc(f),d.push(M(f).toString()),f=f.h(),0==c?c=f:0!=f&&c!=f&&(c=null))};a.forEach(e);return lc(d.join(M(b).toString()),c)},pc=function(a){return oc(Array.prototype.slice.call(arguments))},lc=function(a,
b){var c=Pb();a=c?c.createHTML(a):a;return new K(a,b,kc)},qc=/^[a-zA-Z0-9-]+$/,rc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},sc={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},nc=new K(x.trustedTypes&&x.trustedTypes.emptyHTML||"",0,kc);/*

 SPDX-License-Identifier: Apache-2.0
*/
function tc(a){return a instanceof K?M(a):M(a)};var uc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}},vc=function(a){var b=a;return function(){if(b){var c=b;b=null;c()}}};var wc=function(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)},xc=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};var yc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");var N=function(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{Sa(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}},Ac=function(a,b,c){b=void 0===b?!1:b;c=void 0===c?x:c;for(var d=0;c&&40>d++&&(!b&&!N(c)||!a(c));)c=zc(c)},zc=function(a){try{var b=a.parent;if(b&&b!=a)return b}catch(c){}return null},Bc=function(){if(!globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},O=function(a,
b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)},Dc=uc(function(){return Qa(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Cc)||1E-4>Math.random()}),Ec=uc(function(){return Cc("MSIE")}),Cc=function(a){return-1!=Fa().indexOf(a)},Fc=/https?:\/\/[^\/]+/,Gc=function(a){return(a=Fc.exec(a))&&a[0]||""},Hc=/^([0-9.]+)px$/,Ic=function(a){return(a=Hc.exec(a))?+a[1]:null},Jc=function(a,b){try{return!(!a.frames||!a.frames[b])}catch(c){return!1}},
Kc=function(){var a=window;if("number"!==typeof a.goog_pvsid)try{Object.defineProperty(a,"goog_pvsid",{value:Math.floor(Math.random()*Math.pow(2,52)),configurable:!1})}catch(b){}return Number(a.goog_pvsid)||-1},Lc=function(){return new Promise(function(a){setTimeout(function(){return void a(void 0)},500)})},Mc=function(a,b){b=void 0===b?document:b;return b.createElement(String(a).toLowerCase())};var Nc=function(a,b){var c=void 0===c?!1:c;var d=a.ampInaboxIframes=a.ampInaboxIframes||[],e=function(){};b&&d.push(b);if(!a.ampInaboxInitialized){a.ampInaboxPendingMessages=a.ampInaboxPendingMessages||[];var f=function(h){if(a.ampInaboxInitialized)var g=!0;else{var k,l="amp-ini-load"===h.data;if(a.ampInaboxPendingMessages&&!l&&(k=/^amp-(\d{15,20})?/.exec(h.data))&&(a.ampInaboxPendingMessages.push(h),k=k[1],!(a.ampInaboxInitialized||k&&!/^\d{15,20}$/.test(k)||a.document.querySelector('script[src$="amp4ads-host-v0.js"]')))){h=
a.document;var m;k?m=Vb({ampVersion:k}):m=Ub(D(new C(Hb,"https://cdn.ampproject.org/amp4ads-host-v0.js")));k=Mc("SCRIPT",h);k.src=Rb(m);var p;(g=(m=null==(p=(g=(k.ownerDocument&&k.ownerDocument.defaultView||window).document).querySelector)?void 0:p.call(g,"script[nonce]"))?m.nonce||m.getAttribute("nonce")||"":"")&&k.setAttribute("nonce",g);(g=h.getElementsByTagName("script")[0])&&g.parentNode&&g.parentNode.insertBefore(k,g)}g=!1}g&&e()};c||d.google_amp_listener_added||(d.google_amp_listener_added=
!0,wc(a,"message",f),e=function(){xc(a,"message",f)})}};var Oc=function(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};var Pc=function(a){this.g=a||{cookie:""}};
Pc.prototype.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.Wa;d=c.Xa||!1;var f=c.domain||void 0;var h=c.path||void 0;var g=c.Va}if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===g&&(g=-1);this.g.cookie=a+"="+b+(f?";domain="+f:"")+(h?";path="+h:"")+(0>g?"":0==g?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*g)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+
e:"")};Pc.prototype.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(";"),e=0,f;e<d.length;e++){f=wa(d[e]);if(0==f.lastIndexOf(c,0))return f.slice(c.length);if(f==a)return""}return b};function Qc(a,b,c){b=kb(b)&&"null"!==c.origin?c.document.cookie:null;return null===b?null:(new Pc({cookie:b})).get(a)||""};var Rc=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)"),Vc=function(a){a=a||Sc();for(var b=new Tc(x.location.href,!1),c=null,d=a.length-1,e=d;0<=e;--e){var f=a[e];!c&&Rc.test(f.url)&&(c=f);if(f.url&&!f.ba){b=f;break}}e=null;f=a.length&&a[d].url;0!=b.depth&&f&&(e=a[d]);return new Uc(b,e,c)},Sc=function(){var a=x,b=[],c=null;do{var d=a;if(N(d)){var e=d.location.href;c=d.document&&d.document.referrer||null}else e=c,c=null;b.push(new Tc(e||""));try{a=d.parent}catch(f){a=null}}while(a&&
d!=a);d=0;for(a=b.length-1;d<=a;++d)b[d].depth=a-d;d=x;if(d.location&&d.location.ancestorOrigins&&d.location.ancestorOrigins.length==b.length-1)for(a=1;a<b.length;++a)e=b[a],e.url||(e.url=d.location.ancestorOrigins[a-1]||"",e.ba=!0);return b},Uc=function(a,b,c){this.g=a;this.h=b;this.i=c},Tc=function(a,b){this.url=a;this.ba=!!b;this.depth=null};function Wc(a,b,c){a.google_image_requests||(a.google_image_requests=[]);var d=Mc("IMG",a.document);if(c){var e=function(){if(c){var f=a.google_image_requests,h=Ga(f,d);0<=h&&Array.prototype.splice.call(f,h,1)}xc(d,"load",e);xc(d,"error",e)};wc(d,"load",e);wc(d,"error",e)}d.src=b;a.google_image_requests.push(d)}
function Xc(a){var b=void 0===b?!1:b;var c;if(c=x.navigator)c=x.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&x.navigator.sendBeacon?x.navigator.sendBeacon(a):Wc(x,a,void 0===b?!1:b)}
var Zc=function(a){var b=void 0===b?!1:b;var c="https://pagead2.googlesyndication.com/pagead/gen_204?id=dtt_err";O(a,function(d,e){d&&(c+="&"+e+"="+encodeURIComponent(d))});Yc(c,b)},Yc=function(a,b){var c=window;b=void 0===b?!1:b;c.fetch?c.fetch(a,{keepalive:!0,credentials:"include",redirect:"follow",method:"get",mode:"no-cors"}):Wc(c,a,void 0===b?!1:b)};var $c=function(a,b){this.j=void 0===a?4E3:a;this.i=void 0===b?"&":b;this.h={};this.l=0;this.g=[]},ad=function(a,b){var c={};c[a]=b;return[c]},cd=function(a,b,c,d,e){var f=[];O(a,function(h,g){(h=bd(h,b,c,d,e))&&f.push(g+"="+h)});return f.join(b)},bd=function(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],h=0;h<a.length;h++)f.push(bd(a[h],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=
e||0,2>e?encodeURIComponent(cd(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))},P=function(a,b,c){a.g.push(b);a.h[b]=c},Q=function(a,b,c,d){a.g.push(b);a.h[b]=ad(c,d)},Nd=function(a,b,c,d){b=b+"//"+c+d;var e=dd(a)-d.length;if(0>e)return"";a.g.sort(function(m,p){return m-p});d=null;c="";for(var f=0;f<a.g.length;f++)for(var h=a.g[f],g=a.h[h],k=0;k<g.length;k++){if(!e){d=null==d?h:d;break}var l=cd(g[k],a.i,",$");if(l){l=c+l;if(e>=l.length){e-=l.length;b+=l;c=a.i;break}d=null==d?h:d}}a="";null!=
d&&(a=c+"trn="+d);return b+a},dd=function(a){var b=1,c;for(c in a.h)b=c.length>b?c.length:b;return a.j-3-b-a.i.length-1};var Od=function(a,b,c,d){if(Math.random()<(d||.01))try{if(c instanceof $c)var e=c;else e=new $c,O(c,function(h,g){var k=e,l=k.l++;P(k,l,ad(g,h))});var f=Nd(e,a.g,"pagead2.googlesyndication.com","/pagead/gen_204?id="+b+"&");f&&Xc(f)}catch(h){}};var Td=!1,Ud=null,Vd=function(){this.h={};this.g={};for(var a=[],b=0,c=a.length;b<c;++b)this.g[a[b]]=""},Wd=function(a,b,c){""!=b&&(c?a.g.hasOwnProperty(c)&&(a.g[c]=b):a.h[b]=!0)},Xd=function(a,b){return a.g.hasOwnProperty(b)?a.g[b]:""},Yd=function(a){var b=[];O(a.h,function(c,d){b.push(d)});O(a.g,function(c){""!=c&&b.push(c)});return b};var $d=function(){this.i=Zd;this.h=!0;this.j=this.g},be=function(a,b,c){var d=U;try{var e=b()}catch(g){b=d.h;try{b=d.j(a,new Oc(g,{message:ae(g)}),void 0,c)}catch(k){d.g(217,k)}if(b){var f,h;null==(f=window.console)||null==(h=f.error)||h.call(f,g)}else throw g;}return e},ce=function(a,b,c){return function(){var d=qa.apply(0,arguments);return be(a,function(){return b.apply(void 0,d)},c)}};
$d.prototype.g=function(a,b,c,d,e){e=e||"dcmads-err";try{var f=new $c;Q(f,1,"context",a);b.error&&b.meta&&b.id||(b=new Oc(b,{message:ae(b)}));b.msg&&Q(f,2,"msg",b.msg.substring(0,512));var h=b.meta||{};if(d)try{d(h)}catch(A){}P(f,3,[h]);var g=Vc();g.h&&Q(f,4,"top",g.h.url||"");var k={url:g.g.url||""};if(g.g.url){var l=g.g.url.match(yc),m=l[1],p=l[3],n=l[4];b="";m&&(b+=m+":");p&&(b+="//",b+=p,n&&(b+=":"+n));var v=b}else v="";P(f,5,[k,{url:v}]);Od(this.i,e,f,c)}catch(A){try{Od(this.i,e,{context:"ecmserr",
rctx:a,msg:ae(A),url:g&&g.g.url},c)}catch(L){}}return this.h};var ae=function(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);for(var c;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(d){}}return b};var ee=function(){var a=de,b="aa";if(a.aa&&a.hasOwnProperty(b))return a.aa;b=new a;return a.aa=b};var de=function(){var a={};this.g=function(b,c){return null!=a[b]?a[b]:c};this.h=function(){var b=Lb.g,c=Lb.defaultValue;return null!=a[b]?a[b]:c}},V=function(a){return ee().g(a.g,a.defaultValue)};var fe=function(a){pb.call(this,a)};u(fe,pb);var ge=function(a){this.g=a};var he=function(a,b){this.g=a;this.depth=b},je=function(a){a=a||Sc();var b=Math.max(a.length-1,0),c=Vc(a);a=c.g;var d=c.h,e=c.i,f=[];c=function(g,k){return null==g?k:g};e&&f.push(new he([e.url,e.ba?2:0],c(e.depth,1)));d&&d!=e&&f.push(new he([d.url,2],0));a.url&&a!=e&&f.push(new he([a.url,0],c(a.depth,b)));var h=Ia(f,function(g,k){return f.slice(0,f.length-k)});!a.url||(e||d)&&a!=e||(d=Gc(a.url))&&h.push([new he([d,1],c(a.depth,b))]);h.push([]);return Ia(h,function(g){return ie(b,g)})},ke=function(a,
b){b=b||je();return Ia(b,function(c){var d={};d[a]=c;return d})};function ie(a,b){var c=Pa(b,function(e,f){return Math.max(e,f.depth)},-1),d=Ra(c+2);d[0]=a;Ha(b,function(e){return d[e.depth+1]=e.g});return d}var le=function(a){a=a||je();return Ia(a,function(b){return bd(b)})};var me=function(){};var ne=function(a){void 0!==a.addtlConsent&&"string"!==typeof a.addtlConsent&&(a.addtlConsent=void 0);void 0!==a.gdprApplies&&"boolean"!==typeof a.gdprApplies&&(a.gdprApplies=void 0);return void 0!==a.tcString&&"string"!==typeof a.tcString||void 0!==a.listenerId&&"number"!==typeof a.listenerId?2:a.cmpStatus&&"error"!==a.cmpStatus?0:3},oe=function(a,b){this.h=a;this.g=null;this.j={};this.s=0;this.l=void 0===b?500:b;this.i=null};u(oe,me);
var re=function(a,b){var c={internalErrorState:0},d=vc(function(){return b(c)}),e=0;-1!==a.l&&(e=setTimeout(function(){c.tcString="tcunavailable";c.internalErrorState=1;d()},a.l));pe(a,"addEventListener",function(f,h){e&&(clearTimeout(e),e=0);h&&(c=f);c.internalErrorState=ne(c);0!=c.internalErrorState&&(c.tcString="tcunavailable");if(0!=c.internalErrorState||qe(c))pe(a,"removeEventListener",null,c.listenerId),d()})},se=function(a){return new Promise(function(b){re(a,b)})},pe=function(a,b,c,d){c||
(c=function(){});if("function"===typeof a.h.__tcfapi)a=a.h.__tcfapi,a(b,2,c,d);else if(te(a)){ue(a);var e=++a.s;a.j[e]=c;a.g&&(c={},a.g.postMessage((c.__tcfapiCall={command:b,version:2,callId:e,parameter:d},c),"*"))}else c({},!1)},te=function(a){if(a.g)return a.g;a:{var b=a.h;for(var c=0;50>c;++c){if(Jc(b,"__tcfapiLocator"))break a;if(!(b=zc(b)))break}b=null}a.g=b;return a.g},ue=function(a){a.i||(a.i=function(b){try{var c=("string"===typeof b.data?JSON.parse(b.data):b.data).__tcfapiReturn;a.j[c.callId](c.returnValue,
c.success)}catch(d){}},wc(a.h,"message",a.i))},qe=function(a){if(!1===a.gdprApplies)return!0;void 0===a.internalErrorState&&(a.internalErrorState=ne(a));return"error"===a.cmpStatus||0!==a.internalErrorState||"loaded"===a.cmpStatus&&("tcloaded"===a.eventStatus||"useractioncomplete"===a.eventStatus)?!0:!1};var W={issuerOrigin:"https://attestation.android.com",issuancePath:"/att/i",redemptionPath:"/att/r"},X={issuerOrigin:"https://pagead2.googlesyndication.com",issuancePath:"/dtt/i",redemptionPath:"/dtt/r",getStatePath:"/dtt/s"};ee();
var we=function(a,b,c){var d=this;this.h=a;this.g=[];b&&ve()&&this.g.push(W);c&&this.g.push(X);if(document.hasTrustToken&&!V(Kb)){var e=new Map;this.g.forEach(function(f){e.set(f.issuerOrigin,{issuerOrigin:f.issuerOrigin,state:d.h?1:12,hasRedemptionRecord:!1})});window.goog_tt_state_map=window.goog_tt_state_map&&window.goog_tt_state_map instanceof Map?new Map([].concat(ea(e),ea(window.goog_tt_state_map))):e;window.goog_tt_promise_map&&window.goog_tt_promise_map instanceof Map||(window.goog_tt_promise_map=new Map)}};
u(we,me);
var ve=function(){var a=void 0===a?window:a;a=a.navigator.userAgent;var b=/Chrome/.test(a);return/Android/.test(a)&&b},xe=function(a){a=a.goog_tt_state_map;var b,c=[];(b=null==a?void 0:a.get(W.issuerOrigin))&&c.push(b);(b=null==a?void 0:a.get(X.issuerOrigin))&&c.push(b);return c},ye=function(a){return V(Mb)?!0:a.some(function(b){return b.hasRedemptionRecord})},ze=function(a){a=V(Mb)?a.filter(function(b){return 12!==b.state}).map(function(b){return b.issuerOrigin}):a.filter(function(b){return b.hasRedemptionRecord}).map(function(b){return b.issuerOrigin});if(0==
a.length)return null;a={type:"send-redemption-record",issuers:a,refreshPolicy:"none",signRequestData:V(Mb)?"omit":"include",includeTimestampHeader:!0,additionalSignedHeaders:["sec-time","Sec-Redemption-Record"]};V(Mb);return a},Y=function(a,b,c){var d,e=null==(d=window.goog_tt_state_map)?void 0:d.get(a);e&&(e.state=b,void 0!=c&&(e.hasRedemptionRecord=c))},Ae=function(){var a=W.issuerOrigin+W.redemptionPath,b={keepalive:!0,trustToken:{type:"token-redemption",issuer:W.issuerOrigin,refreshPolicy:"none"}};
Y(W.issuerOrigin,2);return window.fetch(a,b).then(function(c){if(!c.ok)throw Error(c.status+": Network response was not ok!");Y(W.issuerOrigin,6,!0)}).catch(function(c){c&&"NoModificationAllowedError"===c.name?Y(W.issuerOrigin,6,!0):Y(W.issuerOrigin,5)})},Be=function(){var a=W.issuerOrigin+W.issuancePath;Y(W.issuerOrigin,8);return window.fetch(a,{keepalive:!0,trustToken:{type:"token-request"}}).then(function(b){if(!b.ok)throw Error(b.status+": Network response was not ok!");Y(W.issuerOrigin,10);return Ae()}).catch(function(b){if(b&&
"NoModificationAllowedError"===b.name)return Y(W.issuerOrigin,10),Ae();Y(W.issuerOrigin,9)})},Ce=function(){Y(W.issuerOrigin,13);return document.hasTrustToken(W.issuerOrigin).then(function(a){return a?Ae():Be()})},De=function(){Y(X.issuerOrigin,13);if(window.Promise){var a=document.hasTrustToken(X.issuerOrigin).then(function(e){return e}).catch(function(e){return window.Promise.reject({state:19,error:e})}),b=X.issuerOrigin+X.redemptionPath,c={keepalive:!0,trustToken:{type:"token-redemption",refreshPolicy:"none"}};
Y(X.issuerOrigin,16);a=a.then(function(e){return window.fetch(b,c).then(function(f){if(!f.ok)throw Error(f.status+": Network response was not ok!");Y(X.issuerOrigin,18,!0)}).catch(function(f){if(f&&"NoModificationAllowedError"===f.name)Y(X.issuerOrigin,18,!0);else{if(e)return window.Promise.reject({state:17,error:f});Y(X.issuerOrigin,17)}})}).then(function(){return document.hasTrustToken(X.issuerOrigin).then(function(e){return e}).catch(function(e){return window.Promise.reject({state:19,error:e})})}).then(function(e){var f=
X.issuerOrigin+X.getStatePath;Y(X.issuerOrigin,20);return window.fetch(f+"?ht="+e,{trustToken:{type:"send-redemption-record",issuers:[X.issuerOrigin]}}).then(function(h){if(!h.ok)throw Error(h.status+": Network response was not ok!");Y(X.issuerOrigin,22);return h.text().then(function(g){return JSON.parse(g)})}).catch(function(h){return window.Promise.reject({state:21,error:h})})});var d=Kc();return a.then(function(e){var f=X.issuerOrigin+X.issuancePath;return e&&e.srqt&&e.cs?(Y(X.issuerOrigin,23),
window.fetch(f+"?cs="+e.cs+"&correlator="+d,{keepalive:!0,trustToken:{type:"token-request"}}).then(function(h){if(!h.ok)throw Error(h.status+": Network response was not ok!");Y(X.issuerOrigin,25);return e}).catch(function(h){return window.Promise.reject({state:24,error:h})})):e}).then(function(e){if(e&&e.srdt&&e.cs)return Y(X.issuerOrigin,26),window.fetch(b+"?cs="+e.cs+"&correlator="+d,{keepalive:!0,trustToken:{type:"token-redemption",refreshPolicy:"refresh"}}).then(function(f){if(!f.ok)throw Error(f.status+
": Network response was not ok!");Y(X.issuerOrigin,28,!0)}).catch(function(f){return window.Promise.reject({state:27,error:f})})}).then(function(){Y(X.issuerOrigin,29)}).catch(function(e){if(e instanceof Object&&e.hasOwnProperty("state")&&e.hasOwnProperty("error"))if("number"===typeof e.state&&e.error instanceof Error){Y(X.issuerOrigin,e.state);var f=ee().h();Math.random()<=f&&Zc({state:e.state,err:e.error.toString()})}else throw Error(e);else throw e;})}},Ee=function(a){if(document.hasTrustToken&&
!V(Kb)&&a.h){var b=window.goog_tt_promise_map;if(b&&b instanceof Map){var c=[];if(a.g.some(function(e){return e.issuerOrigin===W.issuerOrigin})){var d=b.get(W.issuerOrigin);d||(d=Ce(),b.set(W.issuerOrigin,d));c.push(d)}a.g.some(function(e){return e.issuerOrigin===X.issuerOrigin})&&(a=b.get(X.issuerOrigin),a||(a=De(),b.set(X.issuerOrigin,a)),c.push(a));if(0<c.length&&window.Promise&&window.Promise.all)return window.Promise.all(c)}}};var Fe;if(Fe=Ta){var Ge="IFRAME",He=document;Ge=String(Ge);"application/xhtml+xml"===He.contentType&&(Ge=Ge.toLowerCase());Fe="srcdoc"in He.createElement(Ge)}var Ie=Fe;var Je=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(d){}return!0}(x,!1)?"https:":"http:",Zd,U;Zd=new function(){this.g=Je};U=new $d;var Ke=function(a){U.h=!1;throw Error(a);};var Le={1:{R:"40004000",G:"40004001"}},Me={R:"40004006",G:"40004007"};Le[4]=Me;var Ne={R:"40004008",G:"40004009"};Le[5]=Ne;var Oe={R:"44752204",G:"44752205"};Le[12]=Oe;var Pe={R:"44762123",G:"44762124"};Le[14]=Pe;var Qe={Sa:1,Pa:4,Qa:11,Ra:12,Ta:13},Re={1:1,4:4,5:4,12:11,13:12,14:13};var Se=function(a,b,c){if(a=a.dcmads&&a.dcmads.expts&&a.dcmads.expts[c]){var d=Le[c],e=[],f=0;for(g in d)e[f++]=d[g];if((c=Re[c])?b.g.hasOwnProperty(c)&&""==b.g[c]:1){var h;if(null===Ud){Ud="";try{var g="";try{g=x.top.location.hash}catch(k){g=x.location.hash}g&&(Ud=(h=g.match(/\bdeid=([\d,]+)/))?h[1]:"")}catch(k){}}h=(h=Ud)?(h=h.match(new RegExp("\\b("+e.join("|")+")\\b")))?h[0]:null:null;if(h)a=h;else if(Td)a=null;else b:{if(!Ec()&&!Dc()&&(h=Math.random(),h<a)){h=Bc();a=e[Math.floor(h*e.length)];
break b}a=null}a&&Wd(b,a,c)}}};function Te(a,b){if(b&&b.split){b=b.split(",");for(var c=0;c<b.length;++c){var d=b[c].split("|");1<d.length?Wd(a,d[1],d[0]):Wd(a,d[0])}}};var Ue=function(a){var b=this,c=3===a?"":"dc_";this.l={};var d=function(e){b.l[e]=!0;return e};this.v=d("addtl_consent");this.F=d(c+"adk");this.J=d("amp");this.appId=d(c+"msid");this.K=d(2===a?"chd":"tfcd");this.h=d("click");this.M=d("cesc");this.N=d("uach");this.O=d("chaa");this.P=d("cmpl");this.A=d("gcsr");this.S=d("crlt");this.T=d("xdt");this.U=d("mtfIFPath");this.Y=d("dsmd");this.g=d("dcopt");this.Z=d("deal_id");this.B=d("u_sd");this.ea=d("mtfIFrameRequest");this.fa=d("dv3_deal");this.ga=d(c+
"eid");this.ha=d(c+"xid");this.I=d("gdpr_consent");this.gdprApplies=d("gdpr");this.ia=d("gmcs");this.height=d("h");this.C=d("ifmf");this.ja=d("pc");this.ka=d("dcapp");this.la=d("kw");this.ma=d("mtfLeft");this.na=d(1===a?c+"lat":"lat");this.da=d("ltd");this.oa=d("msdk");this.pa=d("mtfBottomFloat");this.qa=d("mtfLeftFloat");this.ra=d("mtfRightFloat");this.sa=d("mtfTopFloat");d("npa");this.D=d("nel");this.ta=d(c+"omid_p");this.ua=d("ord");d("osdl");this.va=d("osda");this.wa=d("output");this.xa=d("pdid");
this.ya=d("pdidtype");this.za=d("prcl");this.Aa=d(c+"ref");this.Ba=d("trt");this.i=d("rc");this.j=d("rcsrc");this.Ca=d(c+"rxp");this.Da=d(c+"rdid");this.Ea=d("sttr");this.Fa=d(c+"sdk_apis");this.size=d("sz");this.Ga=d("stc");this.Ia=d(3===a?"insv":"dc_ver");this.Ja=d("mtfTop");this.Ka=d("url");this.s=d(c+"rfl");this.La=d("tts");this.Ma=d("tt_state");this.Na=d("tfua");this.Oa=d("u");this.width=d("w")};Ue.prototype.has=function(a){return!!this.l[a]};var Ve=/^data-d([bc]m|v3)-.+/i,We=/^https?%3A.+/i,Xe=/^N\d+\.[A-Za-z0-9._-]*[A-Za-z0-9_-]\.?\/B\d+\.\d+/,Ye=function(a,b){var c=b.attributes;a.g={};for(var d=0;d<c.length;d++){var e=c[d].name;if(Ve.test(e)){var f=e.toLowerCase();e=0==f.indexOf("data-dcm-param-")?"data-dcm-param-"+e.substring(15):f}else e=null;e&&(f=c[d].value,f=null!=f?f:"","data-dcm-click-tracker"==e&&(f=We.test(f)?decodeURIComponent(f):f),a.g[e]=f)}c=a.g["data-dcm-placement"];e=a.g["data-dbm-deal"];f=a.g["data-dv3-deal"];c||e||
f||Ke("No placement or deal attribute set on ins tag");d=a.g["data-dcm-rendering-mode"];c?(a.h=1,(e=Xe.exec(c))||Ke("Invalid placement: "+c),a.C=e[0]):f?(a.h=3,a.v=f):(a.h=2,a.v=e);a.i=new Ue(a.h);switch(d){case "iframe":a.l="iframe";break;case "script":a.l="script";break;default:a.l=2===a.h?"script":"iframe"}a.Y=b;c=b.style;d={};try{d=(x.getComputedStyle?x.getComputedStyle(b,null):b.currentStyle)||{}}catch(h){}if(b=Ic(c.width)||Ic(d.width))a.width=Math.round(b);if(b=Ic(c.height)||Ic(d.height))a.height=
Math.round(b)},Ze=function(a,b){if(b){a=a.B;var c=void 0===c?!1:c;if(qe(b))if(!1===b.gdprApplies||"tcunavailable"===b.tcString||void 0===b.gdprApplies&&!c||"string"!==typeof b.tcString||!b.tcString.length)var d=!0;else{d=void 0===d?"755":d;b:{if(b.publisher&&b.publisher.restrictions&&(c=b.publisher.restrictions["1"],void 0!==c)){c=c[void 0===d?"755":d];break b}c=void 0}0===c?d=!1:b.purpose&&b.vendor?(c=b.vendor.consents,(d=!(!c||!c[void 0===d?"755":d]))&&b.purposeOneTreatment&&"CH"===b.publisherCC?
d=!0:d&&(d=b.purpose.consents,d=!(!d||!d["1"]))):d=!0}else d=!1;a=jb(a,5,d);a=jb(a,2,b.tcString);jb(a,4,b.addtlConsent||"")}else jb(a.B,5,!0)},$e=function(a){var b;a.U&&(b=a.U[1]);return b||null};function af(a,b){O(a,function(c,d){b[d]=c})}function bf(a,b){b.corr=a.corr;b.ts=a.ts;b.aacm={};a.aacm&&af(a.aacm,b.aacm)}function cf(a){return ra(a)&&a.corr&&a.ts?a:null};function df(a,b,c,d,e){try{for(var f=[],h,g=0;(h=c(a))&&a!=b&&100>++g;){for(var k=null,l=d(h),m=0,p=0;p<l.length;++p){if(l[p]==a){k=p-m;break}e(l[p])&&++m}if(null===k)return null;f.unshift(k);a=h}return f}catch(n){return null}}function ef(a){return df(a,a.top,function(b){try{return b.parent}catch(c){return null}},function(b){return b.frames},function(){return!1})}
function ff(a){return df(a,document.documentElement,function(b){return b.parentElement},function(b){return b.children},function(b){return 8==b.nodeType})};var gf=RegExp("https?://d-\\d+\\.ampproject\\.net");function hf(a){return"data-dcm-http-only"in a?"http:":"https:"}function jf(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];P(a,e.priority,kf(b,e))}}function kf(a,b){a=a[b.m];var c=b.X;if(null==a||!c&&0==a.length||null!=b.ca&&a===b.ca)return[];var d={};d[b.u]=null!=c?c:a;return[d]}
function lf(a,b,c,d,e,f){a=a[b];if(!a)return[];a=String(a).toLowerCase();b={};if((void 0===d?0:d)&&("0"==a||"false"==a))b[c]=void 0===f?"0":f;else if("1"==a||"true"==a)b[c]=void 0===e?"1":e;return b[c]?[b]:[]}
function mf(a,b,c,d){var e,f=!1,h=0,g=a.__cmp?1:0;g|=a.__tcfapi?2:0;Ac(function(n){Jc(n,"google_osd_static_frame")&&(h=n==a.top?2:1);Jc(n,"__cmpLocator")&&(g|=4);Jc(n,"__tcfapiLocator")&&(g|=8);if(!N(n))return!1;if(n.mraid)try{e=n.mraid.getVersion()}catch(v){}n.MRAID_ENV&&(e=n.MRAID_ENV.version||void 0,c.M=n.MRAID_ENV.sdk||void 0);n.omid_v1_present&&(f=!0);return!1},!0,a);var k=[];if(e){var l=e.split(".")[0];"2"==l?k.push(5):"3"==l&&k.push(6);c.M&&Q(b,46,d.oa,c.M)}f&&k.push(7);if(l=c.g["data-dcm-api-frameworks"]){l=
l.split?l.split(","):[l];for(var m=0;m<l.length;++m){var p=+l[m];0<p&&-1===k.indexOf(p)&&k.push(p)}}0<k.length&&Q(b,43,d.Fa,k);h&&Q(b,56,d.va,h);g&&Q(b,48,d.P,g)};var nf=/^(?:https?:)?\/\/ad\.doubleclick\.net(?:\/ddm)?\/ad[ij]\/(N[^;]+)/,of=/(^| )dcmads( |$)/;function pf(a,b,c){b.version?(c.rm=b.l||"",c.mode=b.h?b.h+"":"0",b.C?c.plcmt=b.C||"":b.v&&(c.deal=b.v||""),qf(c,b)):(c.ver="88."+(a.dcmads.version.loader||"?"),c.rm="",c.mode="0")}function qf(a,b){a.ver=b.version;b.T&&(a.rxp=1);(b=b.j&&Yd(b.j))&&b.length&&(a.eids=b)}function rf(a,b){if(!a)return null;a=a.split(b+"=");a=a[1]||a[0];return(new RegExp("\\${"+b+"(_[0-9]+)?}","i")).test(a)?null:a}
function sf(a,b){var c=Xd(b.j,11),d=rf(b.g["data-dcm-gdpr-consent"],"gdpr_consent");d&&(b.s=d,b.I="m");d=rf(b.g["data-dcm-gdpr-applies"],"gdpr");/[01]/.test(d)&&(b.gdprApplies=d,b.I="m");if(d=rf(b.g["data-dcm-additional-consent"],"addtl_consent"))b.J=d;if((b.s||null!=b.gdprApplies)&&c!==Oe.G&&1!==b.A)return null;a=new oe(a);return"function"===typeof a.h.__tcfapi||null!=te(a)?a:null}
function tf(a,b,c){Ye(c,b);uf(a,c);var d=sf(a,c);d?se(d).then(function(e){null!=e.gdprApplies&&(c.gdprApplies=e.gdprApplies?"1":"0");c.s=e.tcString||null;"1"!==c.gdprApplies||c.s||(c.s="tcunavailable");c.J=e.addtlConsent||null;c.I="a";Ze(c,e);vf(a,b,c)||wf(a,b,c,!0)}).catch(function(e){U.g(672,e,void 0,sa(pf,a,c))}):(Ze(c),vf(a,b,c)||wf(a,b,c))}
function vf(a,b,c){var d=Xd(c.j,12);if(!d||"44761098"===d||0===c.A||!kb(c.B))return!1;if(1===c.A){var e=new we(!0,!0,!0);c.D=Ee(e);c.A=2}if("44761099"===d||!c.D)return!1;"44761100"===d&&(c.D=Promise.race([c.D,Lc()]));var f=sa(pf,a,c);c.D.then(ce(972,function(){wf(a,b,c,!0)},f)).catch(function(h){U.g(972,h,void 0,f)});return!0}
function wf(a,b,c,d){d=void 0===d?!1:d;if(!xf(a,b,c)){N(a.top)&&/Chrome/.test(a.navigator.userAgent)&&(c.K=!0);2===c.A&&"script"===c.l&&(c.l="iframe",c.S=!0);var e=new $c(15360,1===c.h?";":void 0),f=c.i;var h=c.g,g=c.i,k=h["data-dcm-click-tracker"];if(null==k)var l=[];else{var m=h["data-dcm-landing-page-escapes"]||"";"0"!==m&&"1"!==m&&"2"!==m&&(m="");var p={};3===c.h?(p[g.h]=k,p[g.M]=m):p[g.h+m]=k;null!=h["data-dcm-reverse-click-tracker"]&&(p[g.g]="rcl");l=[p]}P(e,35,l);Q(e,47,f.S,c.O.corr);var n=
c.g,v=[],A;for(A in n)0==A.indexOf("data-dcm-param-")&&v.push(A);if(0==v.length)var L=[];else{var Ja=[];v.sort();for(var qb=0;qb<v.length;qb++){if(0<Ja.length){var rb=void 0,ed=Ja[0],fd={};for(rb in ed)fd[rb]=ed[rb];var gd=fd}else gd={};var hd=gd,id=v[qb],sb=encodeURIComponent(id.substring(15));sb&&!c.i.has(sb)&&(hd[sb]=n[id],Ja.unshift(hd))}L=Ja}P(e,26,L);b:{c:{var R=void 0===R?x:R;var S=R.context||R.AMP_CONTEXT_DATA;if(!S)try{S=R.parent.context||R.parent.AMP_CONTEXT_DATA}catch(Bf){}try{if(S&&S.pageViewId&&
S.canonicalUrl){var jd=S;break c}}catch(Bf){}jd=null}if(jd)var tb=!0;else{for(var kd=c.P,ub=0;ub<kd.length;ub++)if(gf.test(kd[ub].url)){tb=!0;break b}tb=!1}}tb&&Q(e,54,f.J,"1");var Cf=N(a.top)?0:1;Q(e,41,f.T,Cf);var ld=Yd(c.j);ld.length&&Q(e,4,f.ga,ld);c.T&&Q(e,3,f.Ca,"1");Q(e,2,f.Ia,c.version);var md=c.Z;if(md){var vb=(new Date).getTime()-md;99999<vb&&(vb="M");var nd=vb}else nd="";Q(e,57,f.Ea,nd);mf(a,e,c,f);var od;var wb=void 0===wb?x:wb;var pd=wb.devicePixelRatio;(od="number"===typeof pd?+pd.toFixed(3):
null)&&Q(e,13,f.B,od);var qd=c.g["data-dcm-ssaid"];if(qd){var xb={};xb[c.i.xa]=qd;xb[c.i.ya]="ssaid";var rd=[xb]}else rd=[];P(e,30,rd);c.F&&Q(e,37,f.N,Xa(c.F));if(1===c.h)Q(e,5,"sz",c.width&&c.height?c.width+"x"+c.height:"");else{Q(e,1,f.wa,"iframe"==c.l?"html":"js");var yb={};yb[f.width]=c.width;yb[f.height]=c.height;P(e,5,[yb])}var Df=c.Y,Ef=ef(a)||["?"],Ff=ff(Df)||["?"];var sd=Ef.join(",")+":"+Ff.join(","),td=sd.length;if(0==td)var fa=0;else{for(var T=305419896,zb=0;zb<td;zb++)T^=(T<<5)+(T>>2)+
sd.charCodeAt(zb)&4294967295;fa=0<T?T:4294967296+T}Q(e,31,f.F,fa);var Ka=c.i,ud=/^([0-9]+)$/.exec(c.g["data-dcm-refresh-count"]),ha=c.O.aacm;ra(ha)||(ha=c.O.aacm={});var La=ha[fa]||0;ha[fa]=La+1;if(c.N){var Ma=c.N.aacm;ra(Ma)?Ma[fa]=La+1:(Ma=c.N.aacm={},af(ha,Ma))}ud?(Q(e,32,Ka.i,ud[1]),Q(e,58,Ka.j,"p")):La&&(Q(e,32,Ka.i,La),Q(e,58,Ka.j,"h"));var vd=x.navigator;vd.connection&&vd.connection.saveData&&Q(e,45,f.Y,"1");if(2===c.A){Q(e,50,f.La,"1");var Ab=xe(a);Ab&&0<Ab.length&&Q(e,44,f.Ma,Xa(JSON.stringify(Ab)))}kb(c.B)&&
Q(e,51,f.Ga,"1");c.S&&Q(e,52,f.C,"1");var wd,xd;"function"===typeof(null==(wd=a.navigator)?void 0:null==(xd=wd.userAgentData)?void 0:xd.getHighEntropyValues)&&Q(e,53,f.O,"1");jf(e,c.g,[{priority:40,m:"data-dcm-app-id",u:f.appId},{priority:39,m:"data-dcm-publisher-url",u:f.Aa},{priority:25,m:"data-dcm-keywords",u:f.la},{priority:29,m:"data-dcm-impression-exchange-id",u:f.ja},{priority:42,m:"data-dcm-omid-partner",u:f.ta,ca:"[OMIDPARTNER]"}]);P(e,14,lf(c.g,"data-dcm-underage",f.Na));P(e,15,lf(c.g,"data-dcm-child-directed",
f.K));P(e,23,lf(c.g,"data-dcm-limited-ads",f.da));P(e,33,lf(c.g,"data-dcm-purchased-traffic",f.Ba,!0,"1","2"));if(2===c.h||"https:"==hf(c.g))P(e,22,lf(c.g,"data-dcm-limit-ad-tracking",f.na)),P(e,21,kf(c.g,{m:"data-dcm-resettable-device-id",u:f.Da}));c.s&&Q(e,16,f.I,c.s);null!=c.gdprApplies&&Q(e,17,f.gdprApplies,c.gdprApplies);c.I&&Q(e,49,f.A,c.I);c.J&&Q(e,18,f.v,c.J);c.K&&Q(e,20,f.D,"1");if(2===c.h){var yd=c.i;Q(e,0,yd.Z,c.v);var Bb=Vc(c.P);Q(e,38,yd.Ka,Bb.h?Bb.h.url:Bb.g.url)}else{var y=c.i,zd=je(c.P);
1===c.h?P(e,38,ke(y.s,zd)):(Q(e,0,y.fa,c.v),P(e,38,ke(y.s,le(zd))));var Ad=c.g,ia="";"data-dcm-http-only"in Ad&&(ia+="h");"data-dcm-https-only"in Ad&&(ia+="s");""==ia&&(ia="n");Q(e,59,y.za,ia);Q(e,34,y.ua,("00000"+Math.floor(Math.random()*Math.pow(36,6)).toString(36)).slice(-6));var I=c.g;if("data-dcm-multi-bottom-float"in I){var ja=c.i.pa;var F=I["data-dcm-multi-bottom-float"]}else"data-dcm-multi-left-float"in I?(ja=c.i.qa,F=I["data-dcm-multi-left-float"]):"data-dcm-multi-right-float"in I?(ja=c.i.ra,
F=I["data-dcm-multi-right-float"]):"data-dcm-multi-top-float"in I&&(ja=c.i.sa,F=I["data-dcm-multi-top-float"]);ja&&F&&(F=F.split?F.split(","):F,Q(e,11,ja,F));if(Xd(c.j,11)===Oe.G){var Gf=y.ia;if(N(a.top)){var Bd=new ge(a.top),Cd=c.B;var Cb=Cd?Qc("__gads",Cd,Bd.g):null;if(Cb){var Dd=/T=([0-9]+)/.exec(Cb);if(Dd){var Ed=Date.now()/1E3,Fd=+Dd[1];if(Fd<Ed-7884E4)var Na=4;else{var Gd=Ed-Fd;Na=86400>Gd?1:604800>Gd?2:3}}else Na=4}else Na=0;var Hf=Na,Hd=c.B;var If=Hd?Qc("__gpi",Hd,Bd.g):null;var Id=(Cb?"1":
"0")+"-"+(If?"1":"0")+"-"+Hf}else Id="0-0-0";Q(e,55,Gf,Id)}jf(e,c.g,[{priority:27,m:"data-dcm-anonymous-inventory",u:y.g,X:"anid"},{priority:8,m:"data-dcm-disable-iframe-breakout",u:y.ea,X:"false"},{priority:7,m:"data-dcm-dart-iframe-path",u:y.U},{priority:24,m:"data-dcm-external-id",u:y.ha},{priority:36,m:"data-dcm-in-app",u:y.ka,X:"1"},{priority:6,m:"data-dcm-interstitial",u:y.g,X:"1_ist"},{priority:9,m:"data-dcm-left-float",u:y.ma},{priority:10,m:"data-dcm-top-float",u:y.Ja},{priority:28,m:"data-dcm-user-defined",
u:y.Oa}])}if(2===c.h)var Jd=Nd(e,"https:","bid.g.doubleclick.net","/xbbe/bid/xpub?");else{var Kd=hf(c.g);Jd=3===c.h?Nd(e,Kd,"ad.doubleclick.net","/dv3/ad?"):Nd(e,Kd,"ad.doubleclick.net","/ddm/"+("script"==c.l?"adj":"adi")+"/"+c.C+";")}var Oa=Jd;if(1===c.h&&!nf.test(Oa))throw Error("Invalid tag URL: "+Oa);var Db=a.document;if("script"===c.l){var Ld=Xd(c.j,4),Md='<script src="'+Oa+'">\x3c/script>';yf(c);if(Ld===Me.G||Ld===Ne.G||d){var J=zf(Db);b.appendChild(J);var Pd=J,Qd="<body>"+Md+"</body>";if(Ie)Pd.srcdoc=
Qd;else{var Rd=Pd.contentWindow;if(Rd){var Eb=Rd.document;Eb.open("text/html","replace");var Jf=lc(Qd,null);Eb.write(tc(Jf));Eb.close()}}}else{1<b.children.length||1==b.children.length&&"b"==b.children[0].tagName.toLowerCase()||(b.style.display="none");var Kf=lc(Md,null);Db.write(tc(Kf))}}else{var Lf=J=zf(Db);if(2===c.A){var Fb=xe(a);if(Fb&&ye(Fb)){var Sd=ze(Fb);Sd&&Lf.setAttribute("trustToken",JSON.stringify(Sd))}}J.src=Oa;yf(c,J);b.appendChild(J)}J&&Nc(a,J);b.style.textDecoration="none";"iP"===
(a.navigator&&a.navigator.platform||"").substr(0,2)&&"Google Mobile Ads"===c.M&&(b.style.display="block",N(a.top)&&a.top.document&&a.top.document.body&&(a.top.document.body.style.margin="0"))}}function yf(a,b){if(a.K){var c=$e(a);c?(Ac(function(d){d=d.document;if(c&&d.head){var e=Mc("META");d.head.appendChild(e);e.httpEquiv="origin-trial";e.content=c}return!1},!1),b&&(b.allow="attribution-reporting")):a.K=!1}}
function zf(a){a=a.createElement("iframe");var b=a.style;b.width="100%";b.height="100%";b.border="0";b.margin="0";b.padding="0";a.marginWidth="0";a.marginHeight="0";a.scrolling="no";a.frameBorder="0";a.title="advertisement";return a}
function uf(a,b){if(a.ReportingObserver){var c=function(e){e=t(e);for(var f=e.next();!f.done;f=e.next()){var h=f.value;f=h.type;(h=h.body)&&"intervention"===f&&(f={t:f,rid:h.id,tm:b.h,inv:1===b.h?b.C:b.v,ln:h.lineNumber,cn:h.columnNumber,src:h.sourceFile,msg:h.message},qf(f,b),Od(Zd,"dcmror",f,.1))}},d=new a.ReportingObserver(c,{buffered:!0});d.observe();a.addEventListener("unload",function(){c(d.takeRecords());d.disconnect()})}}
function xf(a,b,c){c.F=a.dcmads.uach||null;if(Xd(c.j,13)===Pe.G&&!c.F&&a.dcmads.uachp){var d=sa(pf,a,c);a.dcmads.uachp.then(ce(529,function(){c.F=a.dcmads.uach||"_";wf(a,b,c,!0)},d)).catch(function(e){U.g(529,e,void 0,d)});return!0}return!1};var Z=window;Z.dcmads=Z.dcmads||{};Z.dcmads.version=Z.dcmads.version||{};var Af=new function(){this.v=this.C=null;this.P=Sc();this.F=this.M=this.J=this.I=this.s=this.gdprApplies=null;this.K=!1;this.B=new fe;this.S=!1};
ce(529,function(a,b){var c=a.document;Td=!1;var d=new Vd;for(g in Qe)d.g[Qe[g]]="";try{Te(d,a.dcmads&&a.dcmads.eids);var e=/.*#.*eids=([0-9,|]+)/.exec(a.location.href);e&&Te(d,e[1])}catch(A){}Se(a,d,1);Se(a,d,5);Se(a,d,12);/Chrome/.test(a.navigator.userAgent)&&Se(a,d,14);b.j=d;b.T=!!a.dcmads.version.experiment;b.Z=a.dcmads.startTime||0;b.U=a.dcmads.ots||{};b.version="88."+(a.dcmads.version.loader||"?");b.A=a.dcmads.tts||0;b.D=a.dcmads.ttp||void 0;e=cf(a.goog_ddm_ps);d=null;var f=!0;f=void 0===f?!1:
f;var h=[x.top];var g=[];for(var k=0,l;l=h[k++];){f&&!N(l)||g.push(l);try{if(l.frames)for(var m=0;m<l.frames.length&&1024>h.length;++m)h.push(l.frames[m])}catch(A){}}for(f=0;f<g.length&&(h=g[f],h==a||!(d=cf(h.goog_ddm_ps)));++f);if(e&&d)f=e,h=d,h.ts<f.ts?bf(h,f):bf(f,h);else if(e||d)d&&(a.goog_ddm_ps=e={},bf(d,e));else{e={aacm:{}};f="";for(h=0;10>h;++h)f+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_.!*'()"[Math.floor(70*Math.random())];e=(e.corr=f,e.ts=Date.now(),e);a.goog_ddm_ps=
e}d||(g=g[0],g!==a&&(g.goog_ddm_ps=d={},bf(e,d)));b.O=e;b.N=d;if(!c.body){if(!qc.test("b"))throw Error("");if("B"in sc)throw Error("");d={style:{display:"none"}};e="_";g=null;f="";if(d)for(n in d)if(Object.prototype.hasOwnProperty.call(d,n)){if(!qc.test(n))throw Error("");k=d[n];if(null!=k){h=n;if(k instanceof C)k=D(k);else if("style"==h.toLowerCase()){l=k;if(!ra(l))throw Error("");if(!(l instanceof H)){k=void 0;m="";for(k in l)if(Object.prototype.hasOwnProperty.call(l,k)){if(!/^[-_a-zA-Z0-9]+$/.test(k))throw Error("Name allows only [-_a-zA-Z0-9], got: "+
k);var p=l[k];null!=p&&(p=Array.isArray(p)?p.map(dc).join(" "):dc(p),m+=k+":"+p+";")}l=m?new H(m,bc):cc}k=l instanceof H&&l.constructor===H?l.h:"type_error:SafeStyle"}else{if(/^on/i.test(h))throw Error("");if(h.toLowerCase()in rc)if(k instanceof E)k=Rb(k).toString();else if(k instanceof G)k=Xb(k);else if("string"===typeof k)k=($b(k)||ac).g();else throw Error("");}k.L&&(k=k.g());h=h+'="'+Ea(String(k))+'"';f+=" "+h}}var n="<b"+f;null==e?e=[]:Array.isArray(e)||(e=[e]);!0===Nb.b?n+=">":(g=pc(e),n+=">"+
M(g).toString()+"</b>",g=g.h());(d=d&&d.dir)&&(/^(ltr|rtl|auto)$/i.test(d)?g=0:g=null);n=lc(n,g);c.write(tc(n));c.body||Ke("Body element does not exist")}c=c.getElementsByClassName?c.getElementsByClassName("dcmads"):c.getElementsByTagName("ins");for(n=0;n<c.length;n++)if(d=c[n],(d.getAttribute("data-dcm-placement")||d.getAttribute("data-dbm-deal")||d.getAttribute("data-dv3-deal"))&&of.test(d.className)&&!d.getAttribute("data-dcm-processed")){var v=d;v.setAttribute("data-dcm-processed","y");break}v?
tf(a,v,b):Ke("No ad ins element found")},sa(pf,Z,Af))(Z,Af);}).call(this);
